plugins:
  - jekyll-remote-theme

remote_theme: tuur29/pages-themes-cayman
title: "Australian Curriculum review"
description: "Analysis of Australian Curriculum, focused on Digital Technologies and the ICT Capability."

colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
